### ISSUE TITLE
Approximate two-sex kin using GKP factors?

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#12]
Caswell (2022) notes that "GKP factors" can provide good-enough approximations of two-sex kin given female-only kin estimates. For example, the number of parents is the number of mothers * 2, grandparents are grandmothers * 4, etc.  Is it desirable to add an argument `approximate_male_kin` or something similar to `DemoKin::kin`?

If `approximate_male_kin == TRUE`, then something like this could be used to approximate female+male kin:

```
factors <- c("coa" = 8, "cya" = 8, "d" = 2, "gd" = 4, "ggd" = 8, "ggm" = 8, "gm" = 4, "m" = 2, "nos" = 4, "nys" = 4, "oa" = 4, "ya" = 4, "os" = 2, "ys" = 2)
kin_full$living <- kin_full$living*factors[kin_full$kin]
kin_full$dead <- kin_full$dead*factors[kin_full$kin]
```
The function could also print something like `Using GKP factors to approximate two-sex kin from female only kin age distributions`. 

**References**

Caswell, H. (2022). The formal demography of kinship IV: Two-sex models and their approximations. Demographic Research 47:359–396. doi:[10.4054/DemRes.2022.47.13](https://doi.org/10.4054/DemRes.2022.47.13).

**Comment by IvanWilli** [comment]
@alburezg there is a comparison example in new vignette (`updates` branch). See if this maybe is enough for those that want to apply this approximation.

**Comment by alburezg** [comment]
Yes, having full two-sex models and providing examples of the GKP-factor and androgynous approximation solves this issue. Thanks!
