### ISSUE TITLE
`kin(..., time_invariant=F)` breaks when loading dtplyr

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#17]
I consistently get an error whenever I load `dtplyr` previous to running a `kin(..., time_invariant=F)` function:

```
library(DemoKin)
library(dtplyr)

out <- kin(p = swe_px
      , f = swe_asfr
      , n = swe_pop
      , time_invariant = F
      , output_period = 1950
      , output_kin = "m")
```
> Error in dt_squash_across(x, env, data, j = j) : 
  Problem while evaluating `dplyr::all_of(agrupar)`.
Caused by error in `as_indices_impl()`:
! object 'agrupar' not found

The function works perfectly if I don't load dtplyr before running `kin`.

**Comment by IvanWilli** [comment]
Yes. A data.table arrives when computing kin_summary, dtplyr activates and dont find `across` function. Input converted to data.frame previosuly to avoid conflicts.
