### ISSUE TITLE
`kin2sex` error caused by `pivot_longer`

### ISSUE THREAD

**Issue by thiagocalm** [IvanWilli/DemoKin#22]
Similar to the [maraab23 issues](https://github.com/IvanWilli/DemoKin/issues/20#issue-1617489902), maybe the same problem is happening in the `kin2sex` function. I tested to exclude the `, "value"` in `names_to = "indicator", "value"` and it works well. The problem's lines are [here](https://github.com/IvanWilli/DemoKin/blob/1fe0dfdfc9bdc699e429b1daa49ae5728eb758d4/R/kin2sex.R#L116) and [here](https://github.com/IvanWilli/DemoKin/blob/1fe0dfdfc9bdc699e429b1daa49ae5728eb758d4/R/kin2sex.R#L126), I guess.

**Comment by IvanWilli** [comment]
Hi @thiagocalm , thanks for the issue. I can´t reproduce the error. Can you write the code and the message you get?
Thansk!
