### ISSUE TITLE
'plot_diagram' is not an exported object from 'namespace:DemoKin'

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#3]
I re-installed DemoKin, but get this error:

```
DemoKin::plot_diagram(
+   kins_total = stable[["kins"]]
+   , ego_age = 50
+   )

'plot_diagram' is not an exported object from 'namespace:DemoKin'..
```

**Comment by IvanWilli** [comment]
mmm ok. Is not happening to me, but for sure there is some namespace problem. I should clarify that. I´ll  let you know soon.

**Comment by IvanWilli** [comment]
shlud be solved now. Done more explicit about namespace `DiagrammeR`. Also check that in `DemoKin` namespace you find the other funs

**Comment by alburezg** [comment]
yes, R can find the function now, thanks!
