### ISSUE TITLE
Error in demokin_codes

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#31]
In Demokin::demokin_codes, the labels for 'd' are incorrect. Labels_female says Daughter, but Labels_male: says Brothers, and Labels_2sex: says Sibling. Males for 'd' should be sons and for two-sex children or offspring.

**Comment by IvanWilli** [comment]
It´s solved in the updated version in github, but not in CRAN yet. Please use that version.
We are waiting for Ben´s vignette/tests to do the upload to CRAN. Let´s see what is the best option.
