### ISSUE TITLE
kins() returns duplicate rows?

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#4]
When running the non-stable kin estimates:

`y <- kins(ego_age = 35, year = 2015, P = swe_surv, asfr = swe_asfr, N = swe_pop, stable = F)`

I would expect `y[["kins"]]` there have 35x101 = 3535 rows. However, it has ``y[["kins"]] == 3737` rows, 101 more than expected. It seems like there are duplicates for ego age 0:

`count(y[["kins"]], x)`
 x   n
1   0 202
2   1 101
3   2 101
4   3 101
5   4 101
6   5 101
7   6 101
8   7 101
9   8 101
10  9 101
11 10 101
12 11 101
13 12 101
14 13 101
15 14 101
16 15 101
17 16 101
18 17 101
19 18 101
20 19 101
21 20 101
22 21 101
23 22 101
24 23 101
25 24 101
26 25 101
27 26 101
28 27 101
29 28 101
30 29 101
31 30 101
32 31 101
33 32 101
34 33 101
35 34 101
36 35 101

**Comment by IvanWilli** [comment]
You are wirght Diego. The Ego´s trip was duplicated in 0 because of adding death rows in that age in nonstable case. 
Now solved. Thanks!
