### ISSUE TITLE
Suggested improvements to package

### ISSUE THREAD

**Issue by alburezg** [IvanWilli/DemoKin#6]
- [x] The logical parameter "stable" will be replaced by "time-invariant".
- [x] We will change parameters "focal_year" and "focal_cohort" by "output_period" and "output_cohort": those arguments would only apply for selecting which data wants the user as output in the "time-variant" case.
- [x] Both previous parameters would only apply for the "time-variant" case, and would not be "heard" in other case.
- [x] When no pi or N is supplied as an argument in the "time-variant" case, we would use the stable distribution for mothers´s age and return a message like this "The stable assumption was used for the age distribution of mothers in each input year".

**Comment by IvanWilli** [comment]
Adding a few more:
- [ ] test against Caswell´s papers
- [ ] No `P_b` argument. `f` matrix will imply "effective" births until end of time interval. Include a paragraph in the "using" vignette to show this option. 
- [ ] Finish Multi-stage.

**Comment by alburezg** [comment]
[] use igraph to improve network visualisation

**Comment by alburezg** [comment]
A few more things, ahead of the new release:

- [ ]  Remove ‘importFrom(DiagrammeR,mermaid)’ from NAMESPACE
- [ ] Remove library(igraph) from plot_diagram.R (and add igraph to NAMESPACE?)
- [ ] rename column `death` in `kin_full` to `dead`
- [ ] rename column `count_cum_death` in `kin_summary` to `count_dead`
- [ ] The following script returns an error (I think it should work without calling library(tidyverse)?):

```
library(DemoKin)
swe_surv_2015 <- swe_px[,"2015"]
swe_asfr_2015 <- swe_asfr[,"2015"]
swe_2015 <- kin(U = swe_surv_2015, f = swe_asfr_2015, time_invariant = TRUE)
Error in kin_time_invariant(U = U, f = f, output_kin = output_kin, birth_female = birth_female) %>%  : 
  could not find function "%>%"
```

**Comment by IvanWilli** [comment]
The last error was because "%>%" needs a library to load it. `use_this` has a great [solution](https://usethis.r-lib.org/reference/use_pipe.html). Now solved

**Comment by IvanWilli** [comment]
@alburezg Do we close this? For final testing against Caswell's paper (mostly first) we would need more than visual inspection. Maybe is better to add it in a new list, together with final changes pre CRAN submision, and close this issue.

**Comment by alburezg** [comment]
Agreed, let's close this!
